//! UPF2 pseudopotential file writer.
//!
//! Writes norm-conserving pseudopotentials in UPF2 XML format compatible
//! with Quantum ESPRESSO and DFT-Zig's UPF parser.

const std = @import("std");
const RadialGrid = @import("radial_grid.zig").RadialGrid;
const kb_mod = @import("kb_projector.zig");

pub const PseudopotentialData = struct {
    /// Element symbol
    element: []const u8,
    /// Atomic number
    z: f64,
    /// Number of valence electrons
    z_valence: f64,
    /// XC functional name
    xc_functional: []const u8,
    /// Radial grid r(i)
    r: []const f64,
    /// Radial grid dr(i)
    rab: []const f64,
    /// Local ionic potential V_loc(r) (Ry)
    v_local: []const f64,
    /// KB projectors β_l(r)
    betas: []const BetaData,
    /// D_ij matrix (Ry), stored as flat array [nb × nb]
    dij: []const f64,
    /// Atomic valence charge density ρ_atom(r) * 4πr² (for UPF)
    rho_atom: []const f64,
    /// Nonlinear core correction density ρ_core(r), when enabled.
    nlcc: ?[]const f64 = null,
    /// Maximum angular momentum
    l_max: u32,
    /// Number of mesh points
    mesh_size: usize,
};

pub const BetaData = struct {
    l: u32,
    /// β(r) values on radial grid
    values: []const f64,
    /// Cutoff index (beta is zero beyond this)
    cutoff_index: usize,
};

/// Write a UPF2 pseudopotential file.
pub fn write(data: PseudopotentialData, writer: anytype) !void {
    try writer.writeAll("<UPF version=\"2.0.1\">\n");
    try write_info(writer, data);
    try write_header(writer, data);
    try write_mesh(writer, data);
    try write_local(writer, data);
    try write_nonlocal(writer, data);
    try write_nlcc(writer, data);
    try write_rho_atom(writer, data);
    try writer.writeAll("</UPF>\n");
}

fn write_info(writer: anytype, data: PseudopotentialData) !void {
    try writer.writeAll("  <PP_INFO>\n");
    try writer.print("    Generated by ppgen (DFT-Zig pseudopotential generator)\n", .{});
    try writer.print(
        "    Element: {s}, Z={d:.0}, Z_val={d:.1}\n",
        .{ data.element, data.z, data.z_valence },
    );
    try writer.writeAll("  </PP_INFO>\n");
}

fn write_header(writer: anytype, data: PseudopotentialData) !void {
    try writer.writeAll("  <PP_HEADER\n");
    try writer.print("    generated=\"ppgen\"\n", .{});
    try writer.print("    author=\"DFT-Zig\"\n", .{});
    try writer.print("    date=\"2024-01-01\"\n", .{});
    try writer.print("    element=\"{s}\"\n", .{data.element});
    try writer.print("    pseudo_type=\"NC\"\n", .{});
    try writer.print("    relativistic=\"scalar\"\n", .{});
    try writer.print("    is_ultrasoft=\"F\"\n", .{});
    try writer.print("    is_paw=\"F\"\n", .{});
    try writer.print("    is_coulomb=\"F\"\n", .{});
    try writer.print("    core_correction=\"{s}\"\n", .{if (data.nlcc != null) "T" else "F"});
    try writer.print("    functional=\"{s}\"\n", .{data.xc_functional});
    try writer.print("    z_valence=\"{d:.1}\"\n", .{data.z_valence});
    try writer.print("    total_psenergy=\"0.0\"\n", .{});
    try writer.print("    rho_cutoff=\"0.0\"\n", .{});
    try writer.print("    l_max=\"{d}\"\n", .{data.l_max});
    try writer.print("    l_local=\"-1\"\n", .{});
    try writer.print("    mesh_size=\"{d}\"\n", .{data.mesh_size});
    try writer.print("    number_of_wfc=\"{d}\"\n", .{data.betas.len});
    try writer.print("    number_of_proj=\"{d}\"\n", .{data.betas.len});
    try writer.writeAll("  />\n");
}

fn write_mesh(writer: anytype, data: PseudopotentialData) !void {
    try writer.writeAll("  <PP_MESH>\n");
    try writer.print("    <PP_R type=\"real\" size=\"{d}\">\n", .{data.mesh_size});
    try write_array(writer, data.r, data.mesh_size);
    try writer.writeAll("    </PP_R>\n");
    try writer.print("    <PP_RAB type=\"real\" size=\"{d}\">\n", .{data.mesh_size});
    try write_array(writer, data.rab, data.mesh_size);
    try writer.writeAll("    </PP_RAB>\n");
    try writer.writeAll("  </PP_MESH>\n");
}

fn write_local(writer: anytype, data: PseudopotentialData) !void {
    try writer.print("  <PP_LOCAL type=\"real\" size=\"{d}\">\n", .{data.mesh_size});
    try write_array(writer, data.v_local, data.mesh_size);
    try writer.writeAll("  </PP_LOCAL>\n");
}

fn write_nonlocal(writer: anytype, data: PseudopotentialData) !void {
    try writer.writeAll("  <PP_NONLOCAL>\n");
    for (data.betas, 0..) |beta, idx| {
        try writer.print(
            "    <PP_BETA.{d} type=\"real\" size=\"{d}\" " ++
                "angular_momentum=\"{d}\" cutoff_radius_index=\"{d}\">\n",
            .{ idx + 1, beta.cutoff_index, beta.l, beta.cutoff_index },
        );
        try write_array(writer, beta.values, beta.cutoff_index);
        try writer.print("    </PP_BETA.{d}>\n", .{idx + 1});
    }

    // PP_DIJ
    const nb = data.betas.len;
    try writer.print("    <PP_DIJ type=\"real\" size=\"{d}\">\n", .{nb * nb});
    try write_array(writer, data.dij, nb * nb);
    try writer.writeAll("    </PP_DIJ>\n");
    try writer.writeAll("  </PP_NONLOCAL>\n");
}

fn write_nlcc(writer: anytype, data: PseudopotentialData) !void {
    const nlcc = data.nlcc orelse return;
    if (nlcc.len != data.mesh_size) return error.InvalidPseudopotentialData;
    try writer.print("  <PP_NLCC type=\"real\" size=\"{d}\">\n", .{data.mesh_size});
    try write_array(writer, nlcc, data.mesh_size);
    try writer.writeAll("  </PP_NLCC>\n");
}

fn write_rho_atom(writer: anytype, data: PseudopotentialData) !void {
    try writer.print("  <PP_RHOATOM type=\"real\" size=\"{d}\">\n", .{data.mesh_size});
    try write_array(writer, data.rho_atom, data.mesh_size);
    try writer.writeAll("  </PP_RHOATOM>\n");
}

fn write_array(writer: anytype, data: []const f64, count: usize) !void {
    var col: usize = 0;
    try writer.writeAll("      ");
    for (0..count) |i| {
        try writer.print("{e:22.14}", .{data[i]});
        col += 1;
        if (col == 4) {
            try writer.writeAll("\n      ");
            col = 0;
        }
    }
    if (col > 0) try writer.writeAll("\n");
}

// ============================================================================
// Tests
// ============================================================================

test "UPF writer: produces valid XML structure" {
    // Minimal test data
    const r = [_]f64{ 0.0, 0.01, 0.02, 0.03, 0.04 };
    const rab = [_]f64{ 0.01, 0.01, 0.01, 0.01, 0.01 };
    const v_local = [_]f64{ -1.0, -0.99, -0.95, -0.90, -0.85 };
    const beta_vals = [_]f64{ 0.0, 0.1, 0.2, 0.15, 0.05 };
    const dij = [_]f64{1.5};
    const rho_atom = [_]f64{ 0.0, 0.001, 0.002, 0.002, 0.001 };
    const nlcc = [_]f64{ 0.4, 0.3, 0.2, 0.1, 0.0 };

    const betas = [_]BetaData{
        .{ .l = 0, .values = &beta_vals, .cutoff_index = 5 },
    };

    const data = PseudopotentialData{
        .element = "H",
        .z = 1,
        .z_valence = 1.0,
        .xc_functional = "PZ",
        .r = &r,
        .rab = &rab,
        .v_local = &v_local,
        .betas = &betas,
        .dij = &dij,
        .rho_atom = &rho_atom,
        .nlcc = &nlcc,
        .l_max = 0,
        .mesh_size = 5,
    };

    var buf: [16384]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buf);

    try write(data, &writer);

    const output = writer.buffered();

    // Check key XML tags are present
    try std.testing.expect(std.mem.indexOf(u8, output, "<UPF version=") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "</UPF>") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_HEADER") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_LOCAL") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_NONLOCAL>") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_BETA.1") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_DIJ") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_NLCC") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "<PP_RHOATOM") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "core_correction=\"T\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "element=\"H\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "pseudo_type=\"NC\"") != null);
}

test "UPF writer: rejects NLCC with wrong mesh size" {
    const r = [_]f64{ 0.0, 0.01, 0.02 };
    const rab = [_]f64{ 0.01, 0.01, 0.01 };
    const v_local = [_]f64{ -10.0, -9.5, -9.0 };
    const rho_atom = [_]f64{ 0.0, 0.5, 0.3 };
    const nlcc = [_]f64{ 0.1, 0.2 };
    const dij = [_]f64{};

    const data = PseudopotentialData{
        .element = "He",
        .z = 2,
        .z_valence = 2.0,
        .xc_functional = "PZ",
        .r = &r,
        .rab = &rab,
        .v_local = &v_local,
        .betas = &[_]BetaData{},
        .dij = &dij,
        .rho_atom = &rho_atom,
        .nlcc = &nlcc,
        .l_max = 0,
        .mesh_size = 3,
    };

    var buf: [8192]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buf);
    try std.testing.expectError(error.InvalidPseudopotentialData, write(data, &writer));
}

test "UPF writer: round-trip with parser (structure)" {
    const r = [_]f64{ 0.0, 0.01, 0.02 };
    const rab = [_]f64{ 0.01, 0.01, 0.01 };
    const v_local = [_]f64{ -10.0, -9.5, -9.0 };
    const rho_atom = [_]f64{ 0.0, 0.5, 0.3 };
    const dij = [_]f64{};

    const data = PseudopotentialData{
        .element = "He",
        .z = 2,
        .z_valence = 2.0,
        .xc_functional = "PZ",
        .r = &r,
        .rab = &rab,
        .v_local = &v_local,
        .betas = &[_]BetaData{},
        .dij = &dij,
        .rho_atom = &rho_atom,
        .l_max = 0,
        .mesh_size = 3,
    };

    var buf2: [8192]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buf2);

    try write(data, &writer);

    const output = writer.buffered();
    try std.testing.expect(std.mem.indexOf(u8, output, "z_valence=\"2.0\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "number_of_proj=\"0\"") != null);
}
